### ISSUE TITLE
jsPdfTablePlugin crash into chrome because more rows?!

### ISSUE THREAD

**Issue by XinYiMan** [Prashanth-Nelli/jsPdfTablePlugin#12]
Hello, I used this code to export a table in PDF. It works well on firefix, chrome and opera. But when the lines are so many on chrome crashes. Does anyone know how to fix? thanks

			function generatefromtable(intestazione, target_blank) {
				try{
					var ret = true;
					var data = [], fontSize = 12, height = 0, doc;

					//doc = new jsPDF('p', 'pt', 'a4', true);
					doc = new jsPDF('l', 'pt', 'a4', true); 
					doc.setFont("times", "normal");
					doc.setFontSize(fontSize);
					doc.text(20, 20, intestazione);
					data = [];
					data = doc.tableToJson('tbl_daStampare');
					height = doc.drawTable(data, {
						xstart : 10,
						ystart : 10,
						tablestart : 40,
						marginleft : 10,
						xOffset : 1,
						yOffset : 10
					});
					doc.text(50, height + 20, ''); //messaggio che compare nell'ultima pagina del documento pdf
					//per visualizzare il risultato
target_blank=false;
					if (target_blank==true)
					{
						var blob = doc.output("blob");
						window.open(URL.createObjectURL(blob));
					}else
					{
						doc.output("dataurlnewwindow");
//						doc.output('datauri');
					}
				}catch(err) {
			    		//err.message per avere il testo del messaggio
					ret=false;
				}
				return ret;
			}

**Comment by Prashanth-Nelli** [comment]
Hi @XinYiMan currently am planning to rewrite the plugin with additional features for now use this plugin https://github.com/someatoms/jsPDF-AutoTable which similar to this plugin and has additional features.
