### ISSUE TITLE
Bug in jsPDFAPI.tableToJson

### ISSUE THREAD

**Issue by jb455** [Prashanth-Nelli/jsPdfTablePlugin#14]
The 'table' variable is used before it's defined, on line 90 (and 91) of jspdf.plugin.table.js. Simple enough to fix, just move line 92 up two lines. This applies to both the file in the root directory and the one in Example.

**Comment by Prashanth-Nelli** [comment]
Thanks

**Comment by Prashanth-Nelli** [comment]
Fixed with commit 965bbd87d71fe117a191b741d4bd430ff60a7d0a
