### ISSUE TITLE
Display contents of cell with text wrapped / inline block 

### ISSUE THREAD

**Issue by pkarthikr** [Prashanth-Nelli/jsPdfTablePlugin#6]
Hi, 

How do I get the text to wrap itself inside the cell ?. The issue is, I have a long block of text and the text over runs into the next column. 

I have tried increasing the width from drawColumns method but to no use. Can you help?

**Comment by pkarthikr** [comment]
I did this with your examples -

Here is what I found. I put some text in one of the tds

**Comment by Prashanth-Nelli** [comment]
thanks,i will work on this issue

**Comment by shaunak-12345** [comment]
Hi prashanth, as pkarthikr... same issue i m also facing...
By wat tym u will be able to fix it, i wud be needing it for my current project coz i m thinking to do front end pdf generation using jsPDF and its a report generation so i need table generation that too at very high customization level....

**Comment by Prashanth-Nelli** [comment]
Hi shaunak-12345 i will try to complete within in these two days

**Comment by Prashanth-Nelli** [comment]
shaunak-12345 can you please paste the code here which you used for table creation.then i can understand the problem clearly
