### ISSUE TITLE
Undefined is not a function on line 132 of jspdf.plugin.table.js

### ISSUE THREAD

**Issue by mgrigajtis** [Prashanth-Nelli/jsPdfTablePlugin#7]
I'm attempting to use this plugin to create PDF representation of jQuery datatables.  I am attempting the following:
```
data = $("#crewPerfTable").DataTable().data();
doc.text(0, 0, "Crew Performance");
doc.drawTable(data, {xstart: 10, ystart: 10, tablestart: 10, marginleft: 0});
doc.addPage();
doc.save('PrintOutput.pdf');
```

However I'm getting an Uncaught TypeError: undefined is not a function from line 132 of jspdf.plugin.table.js.

**Comment by Prashanth-Nelli** [comment]
hi @mgrigajtis  i think this error occurred due to empty array you passed to the drawTable function.
      once check whether table to json array working properly or not.

**Comment by mgrigajtis** [comment]
Negative, array is not empty.  In my tests array has 52 objects in it.

**Comment by Prashanth-Nelli** [comment]
hi @mgrigajtis the examples are working properly and am not getting any error.can you please paste that code (both html and js) here or once check the provided examples.

**Comment by Prashanth-Nelli** [comment]
am closing this issue for now
