### ISSUE TITLE
PDF one column header per page

### ISSUE THREAD

**Issue by Nagesh29** [Prashanth-Nelli/jsPdfTablePlugin#8]
Hello Prashanth,

I am using this PDF library and found very useful. But currently I am facing some issue with it.
I am getting the PDF file as a result but it prints only one column on single page.
Same issue with the data as well.
E.g. If I am having 6 columns header, then it takes 6 pages to print those column headers.
Can you please help me with this issue?

**Comment by Prashanth-Nelli** [comment]
Hi @Nagesh29  what happend is your problem solved ?
